# ===========================================================
#   set beam line parameters
# ===========================================================

# // set beam 
/jupiter/generator ParticleBeam 

# //****************************************
# // !!! ATTENTION !!!
# // Particle must be defined at first !!!!
# //****************************************
# // set particle
#/jupiter/beam/particle geantino 
/jupiter/beam/particle opticalphoton 
#/jupiter/beam/particle gamma

# // Multiple scattering 
#/process/inactivate msc
#/process/activate msc

# // set beam energy profile
# // 0 = gaussian profile 
# // 1 = flat profile 
/jupiter/beam/energyprofile 0

# // set energy
#/jupiter/beam/energy 100 GeV
/jupiter/beam/energy 3.64 eV

# // set beamtype 
# // 0 = isotropic mode 
# // 1 = gaussian mode 
#/jupiter/beam/beamtype 1 
/jupiter/beam/beamtype 1 

# // set convergence mode 
# // 0 = divergence mode 
# // 1 = injected from surrounding sphare to beam position 
#/jupiter/beam/convergence 1

# // set range of costheta 
#/jupiter/beam/mincostheta -1 
#/jupiter/beam/maxcostheta 1

# // set beam position profile 
# // 0 = gaussian profile 
# // 1 = flat profile 
/jupiter/beam/positionprofile 0 

# // set beam position 
/jupiter/beam/position 0. 0. 17. cm

# // set beam position sigma 
/jupiter/beam/positionsigmax 0. cm
/jupiter/beam/positionsigmay 0. cm
/jupiter/beam/positionsigmaz 0. cm

# // set beam direction 
/jupiter/beam/direction 0. -1. -1. 

# // set beam direction sigma 
/jupiter/beam/directionsigma 0


# // number of vertices (jet)
/jupiter/beam/numberOfVertices 1

# // number of particles in a vertices
/jupiter/beam/numberOfParticles 1

#/control/execute macros/visdawnf.g4mac

/run/beamOn 100

